// Philippine barangay data keyed by "province|city" (matching PH_PROVINCES / PH_CITIES)

export const PH_BARANGAYS: Record<string, string[]> = {

  // ── AGUSAN DEL NORTE ──────────────────────────────────────────────────────
  "Agusan del Norte|Buenavista": [
    "Agay","Anade","Anislagan","Antao","Basilisa","Camagong","Cubi-cubi","Culit",
    "Jaguimitan","Kinabjangan","La Paz","Magsaysay","Mahaba","New Magallanes",
    "Noche Buena","Poblacion","San Agustin","San Isidro","San Jose","San Roque",
    "Santo Niño","Tagbongabong","Tinaytayan",
  ],
  "Agusan del Norte|Butuan City": [
    "Ambago","Amparo","Ampayon","Anticala","Antongalon","Aupagan","Baan KM 3",
    "Baan Riverside","Babag","Bading","Bancasi","Banza","Baobaoan","Basag",
    "Bayanihan","Bilay","Bit-os","Bitan-agan","Bobon","Bonbon","Bugabus",
    "Bugsukan","Buhangin","Cabcaban","Calibunan","Canayugan","Catalan","Culi",
    "Dankias","De Oro","Don Francisco","Doongan","Dulag","Dumalagan","Florida",
    "Humabon","Imadejas","Kinamlutan","Langihan","Lapu-lapu","Libertad","Limaha",
    "Los Angeles","Lumbocan","Maguinda","Mahay","Mahogany","Maibu","Mandamo",
    "Manila de Bugabus","Maon","Masao","Maug","Nongnong","Obrero","Ong Yiu",
    "Pagatpatan","Pangabugan","Pinamanculan","Port Poyohon","Rajah Datu",
    "Rekina","Riverside","Sagkahan","San Ignacio","San Mateo","San Vicente",
    "Sikatuna","Silongan","Sumilihon","Tagabaca","Tagmamarkay","Tagpangi",
    "Tiniwisan","Tungao","Urduja","Villa Kananga",
  ],
  "Agusan del Norte|Cabadbaran City": [
    "Calibunan","Cambuayon","Camp 4","Comagascas","Concepcion","Del Pilar",
    "Katugasan","Kinabjangan","La Paz","Mabini","Mahaba",
    "Poblacion 1","Poblacion 2","Poblacion 3","Poblacion 4","Poblacion 5",
    "Poblacion 6","Poblacion 7","Poblacion 8","Poblacion 9","Poblacion 10",
    "San Isidro","Talisay","Tolosa","Ubojan","Visita",
  ],
  "Agusan del Norte|Carmen": [
    "Cahayagan","Gosoon","Mabini","Malapong","Manapa","Mao","New Visayas",
    "Poblacion","Rojales","San Agustin","San Isidro","San Luis","San Roque","Tagcatong",
  ],
  "Agusan del Norte|Jabonga": [
    "A. Beltran","Bangonay","Bunga","Campo","Kianggat","Madiangao","Magdaong",
    "Maraiging","Poblacion","San Jose","San Pablo","Santo Niño","Sinobong","Taglibas",
  ],
  "Agusan del Norte|Kitcharao": [
    "Bangayan","Canaway","Crossing","Hinimbangan","Kinalum","Linonggatan",
    "Poblacion","San Antonio","San Isidro","San Roque","Santa Filomena","Sangay","Songkoy",
  ],
  "Agusan del Norte|Las Nieves": [
    "Ambohao","Anibongan","Aupagan","Bunga","Caimpugan","Dansuli","Guinabsan",
    "Langasian","Mahaba","Maitom","Malaonao","Mangobong","Manoligao",
    "Pagatpatan","Poblacion","San Isidro","Taod-oy",
  ],
  "Agusan del Norte|Magallanes": [
    "Alibago","Bolhoon","Cahayagan","Cawilan","Del Pilar","Kolambog",
    "Langasian","Macalong","Poblacion","Tagbongabong",
  ],
  "Agusan del Norte|Nasipit": [
    "Aclan","Alubijid","Camagong","Codcod","Duro","Gusa","Jagupit",
    "La Paz","Lingayao","Poblacion","Punta","Talisay","Triangulo",
  ],
  "Agusan del Norte|Remedios T. Romualdez": [
    "Aserda","Basa","Dolorosa","Lakewood","Lower Caasinan","Panaytayon",
    "Poblacion","San Pablo","Upper Caasinan","Wawa",
  ],
  "Agusan del Norte|Santiago": [
    "Asuncion","Ate-ason","Bundanao","Kauswagan","Mabini","Macapagal",
    "Macaranas","Mahaba","Malpoc","Mamunga","Matin-ao","Pilar","Poblacion","Poniente",
  ],
  "Agusan del Norte|Tubay": [
    "Binuangan","Bood","Causwagan","Doña Rosario","Hanap","Lawigan",
    "Maguinda","New Tubay","Poblacion 1","Poblacion 2","Tubay",
  ],

  // ── AGUSAN DEL SUR ────────────────────────────────────────────────────────
  "Agusan del Sur|Bayugan City": [
    "Berseba","Bucac","Causwagan","Guinoyuran","La Paz","Lipa","Magsaysay",
    "Marcelina","Maygatasan","Nueva Gracia","Noli","Pinagalaan",
    "Poblacion 1","Poblacion 2","Poblacion 3","Poblacion 4","Poblacion 5",
    "Poblacion 6","Poblacion 7","Poblacion 8","Santa Ana","Taglatawan","Verdu","Wao",
  ],
  "Agusan del Sur|Bunawan": [
    "Consuelo","Imelda","Libertad","Mambalili","Napo","New Visayas","Noli",
    "Poblacion","San Andres","San Marcos","Santa Cruz","Santa Lucia","Tungao",
  ],
  "Agusan del Sur|Esperanza": [
    "Agsayan","Calaitan","Cayawan","Guinoyoran","Jabonga","Kicharao","Lacaron",
    "Mabago","Macar","Magabaron","Maygatasan","Nueva Gracia","Panaligao",
    "Pansayan","Pagsabangan","Poblacion","Santa Cruz","San Isidro","Sanagdon",
    "Tagbongabong","Tinago",
  ],
  "Agusan del Sur|La Paz": [
    "Aguinaldo","Agusan Small","Bunot","Del Monte","Esperanza","Guiawan",
    "Kahayag","Kasapa II","Langkila-an","Libertad","Magsaysay","Panaytayon",
    "Salvacion","San Ricardo","San Vicente","Taglatawan","Verdu","Villa Paz",
  ],
  "Agusan del Sur|Loreto": [
    "Arellano","Aurora","Basak","Cagas-angan","Cantiasay","Cauyonan",
    "Doña Andrea","Nueva Gracia","Nuevo Ipet","Pag-asa","Poblacion","Tinago",
  ],
  "Agusan del Sur|Prosperidad": [
    "Agsayan","Anahawan","Aurora","Basa","Behia","Buenavista","Bunawan",
    "Cagbaoto","Doña Rosario","Florida","Golden","Goma","Guiria","Happy Valley",
    "Kagaangay","Kamboyo","Kasapa I","Kasapa II","Lagundi","Libertad",
    "Los Angeles","Lucena","Luna","Magsaysay","Maunlad","Maygatasan",
    "New Pacencia","Noli","Pagsabangan","Pag-asa","Poblacion","Sagunto",
    "San Agustin","San Luis","San Marcos","San Martin","Santa Cruz",
    "Santa Elena","Santa Josefa","Santa Teresa","Santo Niño","Tinago",
    "Tiongson","Valentin",
  ],
  "Agusan del Sur|Rosario": [
    "Balungay","Bolhoon","Busay","Cagbaoto","Flores","Libertad",
    "New Butuan","Patin-ay","Poblacion","Singat",
  ],
  "Agusan del Sur|San Francisco": [
    "Alegria","Ambayon","Angas","Anonas","Bayugan","Bitan-agan","Bulonay",
    "Cabadisan","Calibunan","Cayawan","Doña Belen","Florida","La Paz",
    "Magsaysay","Manila","New Magsaysay","New Visayas","Noli","Pagas",
    "Poblacion","Quiloay","Rogongon","San Isidro","San Vicente","Santa Cruz",
    "Santa Maria","Santiago","Santo Tomas","Tagbobonga","Verdu",
  ],
  "Agusan del Sur|San Luis": [
    "Angas","Calibunan","Del Carmen","Florida","Kintaotao","La Paz",
    "New Calamba","New Society","Poblacion","Sagunto","San Agustin","San Roque",
  ],
  "Agusan del Sur|Santa Josefa": [
    "Basa","Cagas-angan","Causwagan","Guiawa","Kasuba","La Paz","Loreto",
    "New Calamba","New Pangasinan","New Society","Poblacion","San Pablo","Tagbongabong",
  ],
  "Agusan del Sur|Sibagat": [
    "Abayon","Anahawan","Aurora","Bocawe","Bon-ot","Buenasuerte","Cagbas",
    "Doña Flavia","El Rio","Golden","Kapatungan","Kolambugan","Lim","Maaslum",
    "New Tubay","Nituan","Nueva Gracia","Ocaña","Pagas","Poblacion",
    "Sabanal","San Isidro","San Pedro","Santa Cruz","Tabon-tabon",
  ],
  "Agusan del Sur|Talacogon": [
    "Betek","Camp I","Camp III","Gibong","Kirorog","La Suerte","Labnig",
    "Maharlika","Nueva Era","Panaytayon","Poblacion","San Isidro","Sabang",
  ],
  "Agusan del Sur|Trento": [
    "Buhang","Cagbaoto","Dao","Dimayon","Don Roque Ablan","Kioya","Langkilaan",
    "Magsaysay","New Visayas","Poblacion","San Isidro","Salvacion",
    "Socoy","Tigao","Tunggayon","Urbiztondo",
  ],
  "Agusan del Sur|Veruela": [
    "Anitapan","Aurora","Causwagan","Dao","Katipunan","Kimonos","Lagunde",
    "Panaytayon","Paya","Poblacion","San Carlos","Santa Fe","Santo Niño",
  ],

  // ── SURIGAO DEL NORTE ────────────────────────────────────────────────────
  "Surigao del Norte|Surigao City": [
    "Alegria","Anao-aon","Armada","Baybay","Bilabid","Bonifacio","Buenavista",
    "Capalayan","Catadman","Corregidor","Danao","Day-asan","Ipil","Libuac",
    "Lipata","Lisondra","Luna","Mabua","Mabuhay","Mat-i","Nabago","Nanaman",
    "Poctoy","Poblacion","San Juan","Sidlakan","Silop","Sugbay","Taft",
    "Togbongon","Trinidad","Tictagon","Umapad",
  ],
  "Surigao del Norte|Claver": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Cagdianao","Daywan",
    "Hayanggabon","Hitablayan","Kanaway","Ladgaron","Lapinigan","Loquinon",
    "Magpayang","Magtangale","Panatao","Tayaga","Urbiztondo","Wangke",
  ],
  "Surigao del Norte|Dapa": [
    "Bagakay","Bak-as","Caub","Del Carmen","Dinagat","Esperanza","Hanod",
    "Helino","Idao","Mabini","Malinao","Maputi","Momon","Ngan","Pad-pad",
    "Panitian","Poblacion","Quezon","Roxas","San Vicente","Santa Cruz",
    "Tawin-tawin","Tigbao","Tres de Mayo","Union","Wakat",
  ],
  "Surigao del Norte|Del Carmen": [
    "Bitoon","Catangnan","Consuelo","Domino","Esperanza","Ilaya","Libertad",
    "Lo-oc","Lombocan","Mabini","Mahayahay","Matin-ao","Olave","Poblacion",
    "San Fernando","San Jose","Santa Cruz","Tag-ibo","Tigbao","Tina",
  ],
  "Surigao del Norte|General Luna": [
    "Anajawan","Borbobot","Cabitoonan","Catigbian","Comagac","La Januza",
    "Libertad","Lomboy","Lubo-og","Maasin","Mabua","Poblacion","San Roque",
    "Sogod","Sta. Cruz","Sto. Niño",
  ],
  "Surigao del Norte|Mainit": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Bobontugan","Cantugas","Dayano","Magpayang","Matin-ao","Roxas","Siana",
    "Silop","Tagbuyawan","Toconan",
  ],
  "Surigao del Norte|Malimono": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Hanigad","Lahi",
    "Mabuhay","Magpayang","San Isidro","Sison","Tinago","Tina",
  ],
  "Surigao del Norte|San Francisco": [
    "Alipao","Aurora","Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)",
    "Bugas","Cabugo","Cagdianao","Comalab","Mahayahay","Mabuhay",
    "Peñafrancia","Salvacion","Santo Niño","Tagbubonga","Tigbao",
  ],
  "Surigao del Norte|Socorro": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Doña Helene","Jubang","La Union","Magsaysay","Mabuhay","Pamosaingan",
    "San Juan","San Roque","Santa Cruz","Santa Fe","Socorro","Sudlon",
  ],
  "Surigao del Norte|Tubod": [
    "Alambique","Anahao","Anislagan","Bgy. 1 (Pob.)","Bgy. 2 (Pob.)",
    "Bgy. 3 (Pob.)","Caloc-an","Cawilan","Dahican","Gamuton","Magpayang",
    "Mabuhay","Pangabuan","Santo Niño","Tinago",
  ],

  // ── SURIGAO DEL SUR ──────────────────────────────────────────────────────
  "Surigao del Sur|Tandag City": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Bgy. 5 (Pob.)","Bgy. 6 (Pob.)","Bgy. 7 (Pob.)","Bgy. 8 (Pob.)",
    "Bioto","Bongtod","Buenavista","Dagocdoc","Mabua","Mabuhay","Manyayao",
    "Odiong","Pandanon","Pangi","San Agustin","San Antonio","San Carlos",
    "San Miguel","Santiago","Telaje",
  ],
  "Surigao del Sur|Bislig City": [
    "Bucto","Burboanan","Caguyao","Coleto","Cumawas","Dao","Kahayag",
    "Labisma","Lawigan","Maharlika","Mangagoy","Mone","Pagtilaan",
    "Patin-ay","Poblacion","San Fernando","San Isidro","San Jose",
    "San Vicente","Tabon","Taguibo","Tumanan",
  ],
  "Surigao del Sur|Hinatuan": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Bgy. 5 (Pob.)","Bgy. 6 (Pob.)","Bgy. 7 (Pob.)","Bgy. 8 (Pob.)",
    "Bgy. 9 (Pob.)","Alegria","Bugsoc","Cambatong","Campa","Cancavan",
    "Dugmanon","Jubang","Kinachara","Loyola","Magtangale","Mamis",
    "San Jose","Sto. Niño","Talavera","Tíal","Tinaogan",
  ],
  "Surigao del Sur|Lianga": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Anibongan","Banahao","Bombong","Diatagon","Ganayon","Liatimco",
    "Manyayao","Pagtilaan","Punta","San Isidro","San Roque","Tago",
    "Tambis","Tawagan",
  ],
  "Surigao del Sur|Tago": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Bgy. 5 (Pob.)","Bgy. 6 (Pob.)","Bgy. 7 (Pob.)","Bgy. 8 (Pob.)",
    "Alegria","Antipolo","Arorogan","Cabugo","Cagdapao","Cambagang",
    "Campalanas","Diaz","Hinayak","Jubang","La Paz","La Purisima",
    "Lapinigan","Libertad","Loreto","Mabua","Magobawok","Mangodiay",
    "Matiao","Pag-asa","Panayvan","Pantukan","Punta","San Isidro",
    "San Pedro","Santa Fe","Santo Niño","Siana","Sibahay","Tibaleg",
    "Tigbao","Tinago",
  ],

  // ── DINAGAT ISLANDS ───────────────────────────────────────────────────────
  "Dinagat Islands|Basilisa": [
    "Anonang","Catadman","Estrella","Kinwherever","Libas","Mabini",
    "New Bucas","Panamaon","Poblacion","San Fernando","San Jose","Santa Cruz",
    "Santiago","Señora","Tigbao",
  ],
  "Dinagat Islands|Cagdianao": [
    "Alubijid","Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)",
    "Cagdianao","Cainglet","Edera","Mabini","Magpayang","Santa Cruz","Tigbao",
  ],
  "Dinagat Islands|Dinagat": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Bgy. 5 (Pob.)","Bgy. 6 (Pob.)","Cayetano","Magsaysay","Mabini",
    "San Jose","Santa Cruz",
  ],
  "Dinagat Islands|Libjo": [
    "Albor","Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)",
    "Dinagat","Justiniana Edera","Magsaysay","Poniente","San Miguel","Tigbao",
  ],
  "Dinagat Islands|Loreto": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Bgy. 5 (Pob.)","Cabuyoan","Esperanza","Legaspi","Magsaysay",
    "Mapawa","Panaytayon","San Jose",
  ],
  "Dinagat Islands|San Jose": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Bgy. 5 (Pob.)","Bgy. 6 (Pob.)","Bgy. 7 (Pob.)","Bgy. 8 (Pob.)",
    "Allangigan","Bongbong","Cagdao","Cayetano","Magsaysay",
    "Mabini","Mahayahay","Pakwan","San Roque","Santa Cruz","Tigbao",
  ],
  "Dinagat Islands|Tubajon": [
    "Bgy. 1 (Pob.)","Bgy. 2 (Pob.)","Bgy. 3 (Pob.)","Bgy. 4 (Pob.)",
    "Coring","Diaz","Imelda","Mabini","Magsaysay","San Roque","Tigbao",
  ],

  // ── METRO MANILA / NCR ───────────────────────────────────────────────────
  "Metro Manila|Quezon City": [
    "Apolonio Samson","Bagbag","Bagong Lipunan ng Crame","Bagong Pag-asa",
    "Bagong Silangan","Bagumbuhay","Bagumbayan","Bahay Toro","Batasan Hills",
    "Bayanihan","Blue Ridge A","Blue Ridge B","Botocan","Central","Commonwealth",
    "Culiat","Damar","Damayan Lagi","Del Monte","Dioquino Zobel","Don Manuel",
    "Escopa I","Escopa II","Escopa III","Escopa IV","Fairview","Greater Lagro",
    "Gulod","Holy Spirit","Horseshoe","Immaculate Concepcion","Kaligayahan",
    "Kalusugan","Kamuning","Katipunan","Kaunlaran","Kristong Hari","Krus na Ligas",
    "Laging Handa","Libis","Lourdes","Loyola Heights","Maharlika","Malaya",
    "Manresa","Mangga","Mariblo","Marilag","Masagana","Masambong","Matatag",
    "Milagrosa","N. S. Amoranto","Nagkaisang Nayon","Nayong Kanluran","New Era",
    "Novaliches Proper","Obrero","Old Capitol Site","Pag-ibig sa Nayon",
    "Pahina Central","Pahina San Miguel","Paligsahan","Pinyahan","Pinagkaisahan",
    "Project 6","Quirino 2-A","Quirino 2-B","Quirino 2-C","Quirino 3-A",
    "Ramon Magsaysay","San Agustin","San Bartolome","San Isidro Labrador",
    "San Isidro Galas","San Jose","San Martin de Porres","San Roque","Santa Cruz",
    "Santa Lucia","Santa Monica","Santo Cristo","Santo Niño","Santol","Sauyo",
    "Siena","Sikatuna Village","Silangan","Socorro","South Triangle","Tagumpay",
    "Talayan","Tatalon","Teachers Village East","Teachers Village West",
    "U.P. Campus","Ugong Norte","Veterans Village","White Plains",
  ],
  "Metro Manila|Manila": [
    "Barangay 1","Barangay 2","Barangay 3","Barangay 4","Barangay 5",
    "Barangay 6","Barangay 7","Barangay 8","Barangay 9","Barangay 10",
    "Barangay 11","Barangay 12","Barangay 13","Barangay 14","Barangay 15",
    "Barangay 16","Barangay 17","Barangay 18","Barangay 19","Barangay 20",
    "Barangay 21","Barangay 22","Barangay 23","Barangay 24","Barangay 25",
    "Barangay 26","Barangay 27","Barangay 28","Barangay 29","Barangay 30",
    "Barangay 31","Barangay 32","Barangay 33","Barangay 34","Barangay 35",
    "Barangay 36","Barangay 37","Barangay 38","Barangay 39","Barangay 40",
    "Barangay 41","Barangay 42","Barangay 43","Barangay 44","Barangay 45",
    "Barangay 46","Barangay 47","Barangay 48","Barangay 49","Barangay 50",
    "Barangay 51","Barangay 52","Barangay 53","Barangay 54","Barangay 55",
    "Barangay 56","Barangay 57","Barangay 58","Barangay 59","Barangay 60",
    "Barangay 61","Barangay 62","Barangay 63","Barangay 64","Barangay 65",
    "Barangay 66","Barangay 67","Barangay 68","Barangay 69","Barangay 70",
    "Barangay 71","Barangay 72","Barangay 73","Barangay 74","Barangay 75",
    "Barangay 76","Barangay 77","Barangay 78","Barangay 79","Barangay 80",
    "Barangay 81","Barangay 82","Barangay 83","Barangay 84","Barangay 85",
    "Barangay 86","Barangay 87","Barangay 88","Barangay 89","Barangay 90",
    "Barangay 91","Barangay 92","Barangay 93","Barangay 94","Barangay 95",
    "Barangay 96","Barangay 97","Barangay 98","Barangay 99","Barangay 100",
    "Barangay 101","Barangay 102","Barangay 103","Barangay 104","Barangay 105",
    "Barangay 106","Barangay 107","Barangay 108","Barangay 109","Barangay 110",
    "Barangay 111","Barangay 112","Barangay 113","Barangay 114","Barangay 115",
    "Barangay 116","Barangay 117","Barangay 118","Barangay 119","Barangay 120",
    "Barangay 121","Barangay 122","Barangay 123","Barangay 124","Barangay 125",
    "Barangay 126","Barangay 127","Barangay 128","Barangay 129","Barangay 130",
    "Barangay 131","Barangay 132","Barangay 133","Barangay 134","Barangay 135",
    "Barangay 136","Barangay 137","Barangay 138","Barangay 139","Barangay 140",
    "Barangay 141","Barangay 142","Barangay 143","Barangay 144","Barangay 145",
    "Barangay 146","Barangay 147","Barangay 148","Barangay 149","Barangay 150",
    "Barangay 151","Barangay 152","Barangay 153","Barangay 154","Barangay 155",
    "Barangay 156","Barangay 157","Barangay 158","Barangay 159","Barangay 160",
    "Barangay 161","Barangay 162","Barangay 163","Barangay 164","Barangay 165",
    "Barangay 166","Barangay 167","Barangay 168","Barangay 169","Barangay 170",
    "Barangay 171","Barangay 172","Barangay 173","Barangay 174","Barangay 175",
    "Barangay 176","Barangay 177","Barangay 178","Barangay 179","Barangay 180",
    "Barangay 181","Barangay 182","Barangay 183","Barangay 184","Barangay 185",
    "Barangay 186","Barangay 187","Barangay 188","Barangay 189","Barangay 190",
    "Barangay 191","Barangay 192","Barangay 193","Barangay 194","Barangay 195",
    "Barangay 196","Barangay 197","Barangay 198","Barangay 199","Barangay 200",
  ],
  "Metro Manila|Makati": [
    "Bangkal","Bel-Air","Carmona","Comembo","East Rembo","Forbes Park",
    "Guadalupe Nuevo","Guadalupe Viejo","Kasilawan","La Paz","Magallanes",
    "Maharlika","Malamig","Palanan","Pembo","Pinagkaisahan","Pio del Pilar",
    "Pitogo","Poblacion","Post Proper Northside","Post Proper Southside",
    "Rizal","San Antonio","San Isidro","San Lorenzo","Santa Cruz",
    "Singkamas","South Cembo","Tejeros","Urbiztondo","Valenzuela","West Rembo",
  ],
  "Metro Manila|Pasig": [
    "Bagong Ilog","Bagong Katipunan","Bambang","Buting","Caniogan","Dela Paz",
    "Kalawaan","Kapasigan","Kapitolyo","Malinao","Manggahan","Maybunga",
    "Oranbo","Palatiw","Pinagbuhatan","Pineda","Rosario","Sagad","San Antonio",
    "San Joaquin","San Jose","San Miguel","San Nicolas","Santa Cruz",
    "Santa Lucia","Santa Rosa","Santolan","Sumilang","Ugong",
  ],
  "Metro Manila|Taguig": [
    "Bagong Tanyag","Bambang","Calzada","Central Bicutan","Central Signal Village",
    "Fort Bonifacio","Hagonoy","Ibayo-Tipas","Katuparan","Ligid-Tipas",
    "Lower Bicutan","Maharlika Village","Napindan","New Lower Bicutan",
    "North Daang Hari","North Signal Village","Palingon","Pinagsama",
    "San Miguel","Santa Ana","South Daang Hari","South Signal Village",
    "Tanyag","Tuktukan","Upper Bicutan","Ususan","Wawa","Western Bicutan",
  ],
  "Metro Manila|Parañaque": [
    "Baclaran","BF Homes","Don Bosco","Don Galo","La Huerta",
    "Marcelo Green Village","Moonwalk","San Antonio","San Dionisio",
    "San Isidro","San Martin de Porres","Santo Niño","Sun Valley","Tambo","Vitalez",
  ],
  "Metro Manila|Marikina": [
    "Barangka","Calumpang","Concepcion Uno","Concepcion Dos","Fortune",
    "Industrial Valley","Jesus dela Peña","Malanday","Marikina Heights",
    "Nangka","Parang","San Roque","Santa Elena","Tañong","Tumana",
  ],
  "Metro Manila|Muntinlupa": [
    "Alabang","Ayala Alabang","Bayanan","Buli","Cupang",
    "Poblacion","Putatan","Sucat","Tunasan",
  ],
  "Metro Manila|Las Piñas": [
    "Almanza Uno","Almanza Dos","B.F. International Village","CAA-BF International",
    "Daniel Fajardo","Elias Aldana","Ilaya","Manuyo Uno","Manuyo Dos",
    "Pamplona Uno","Pamplona Dos","Pamplona Tres","Pilar","Pulang Lupa Uno",
    "Pulang Lupa Dos","Real","Talon Uno","Talon Dos","Talon Tres",
    "Talon Kwatro","Talon Singko",
  ],
  "Metro Manila|Mandaluyong": [
    "Addition Hills","Bagong Silang","Barangka Drive","Barangka Itaas",
    "Barangka Ilaya","Barangka Ibaba","Buayang Bato","Burol","Daang Bakal",
    "Hagdan Bato Itaas","Hagdan Bato Libis","Harapin ang Bukas","Highway Hills",
    "Hulo","Mabini-J. Rizal","Malamig","Mauway","Namayan","New Zañiga",
    "Old Zañiga","Pag-asa","Plainview","Pleasant Hills","Poblacion","San Andres",
    "San Joaquin","Santa Mesa Heights","Santolan","Vergara","Wack-Wack Greenhills",
  ],
  "Metro Manila|San Juan": [
    "Addition Hills","Balong Bato","Batis","Corazon de Jesus","Ermitaño",
    "Greenhills","Isabelita","Kabayanan","Little Baguio","Maytunas","Onse",
    "Pasadena","Pedro Cruz","Progreso","Rivera","Salapan","San Perfecto",
    "Santa Lucia","Santo Niño","West Crame",
  ],
  "Metro Manila|Pasay": [
    "Barangay 1","Barangay 2","Barangay 3","Barangay 4","Barangay 5",
    "Barangay 6","Barangay 7","Barangay 8","Barangay 9","Barangay 10",
    "Barangay 11","Barangay 12","Barangay 13","Barangay 14","Barangay 15",
    "Barangay 16","Barangay 17","Barangay 18","Barangay 19","Barangay 20",
    "Barangay 21","Barangay 22","Barangay 23","Barangay 24","Barangay 25",
    "Barangay 26","Barangay 27","Barangay 28","Barangay 29","Barangay 30",
    "Barangay 31","Barangay 32","Barangay 33","Barangay 34","Barangay 35",
    "Barangay 36","Barangay 37","Barangay 38","Barangay 39","Barangay 40",
    "Barangay 41","Barangay 42","Barangay 43","Barangay 44","Barangay 45",
    "Barangay 46","Barangay 47","Barangay 48","Barangay 49","Barangay 50",
    "Barangay 51","Barangay 52","Barangay 53","Barangay 54","Barangay 55",
    "Barangay 56","Barangay 57","Barangay 58","Barangay 59","Barangay 60",
    "Barangay 61","Barangay 62","Barangay 63","Barangay 64","Barangay 65",
    "Barangay 66","Barangay 67","Barangay 68","Barangay 69","Barangay 70",
    "Barangay 71","Barangay 72","Barangay 73","Barangay 74","Barangay 75",
    "Barangay 76","Barangay 77","Barangay 78","Barangay 79","Barangay 80",
    "Barangay 81","Barangay 82","Barangay 83","Barangay 84","Barangay 85",
    "Barangay 86","Barangay 87","Barangay 88","Barangay 89","Barangay 90",
    "Barangay 91","Barangay 92","Barangay 93","Barangay 94","Barangay 95",
    "Barangay 96","Barangay 97","Barangay 98","Barangay 99","Barangay 100",
    "Barangay 101","Barangay 102","Barangay 103","Barangay 104","Barangay 105",
    "Barangay 106","Barangay 107","Barangay 108","Barangay 109","Barangay 110",
    "Barangay 111","Barangay 112","Barangay 113","Barangay 114","Barangay 115",
    "Barangay 116","Barangay 117","Barangay 118","Barangay 119","Barangay 120",
    "Barangay 121","Barangay 122","Barangay 123","Barangay 124","Barangay 125",
    "Barangay 126","Barangay 127","Barangay 128","Barangay 129","Barangay 130",
    "Barangay 131","Barangay 132","Barangay 133","Barangay 134",
  ],
  "Metro Manila|Malabon": [
    "Acuña","Baritan","Bayan-bayanan","Catmon","Concepcion","Dampalit",
    "Flores","Hulong Duhat","Ibaba","Longos","Maysilo","Muzon","Niugan",
    "Panghulo","Potrero","San Agustin","Santolan","Tañong","Tinajeros","Tonsuya","Tugatog",
  ],
  "Metro Manila|Navotas": [
    "Bagumbayan Norte","Bagumbayan Sur","Bangculasi","Daanghari","Navotas East",
    "Navotas West","North Bay Boulevard North","North Bay Boulevard South",
    "San Jose","San Raphael","San Roque","Sipac-Almacen","Tangos",
  ],
  "Metro Manila|Valenzuela": [
    "Arkong Bato","Balangkas","Bignay","Bisig","Canumay East","Canumay West",
    "Coloong","Dalandanan","Gen. T. de Leon","Isla","Karuhatan","Lawang Bato",
    "Lingunan","Mabolo","Malanday","Malinta","Mapulang Lupa","Marulas",
    "Maysan","Palasan","Parada","Pariancillo Villa","Pasolo","Poblacion",
    "Polo","Punturin","Rincon","Tagalag","Ugong","Viente Reales","Wawang Pulo",
  ],
  "Metro Manila|Caloocan": [
    "Bagong Barrio","Barangay 1","Barangay 2","Barangay 3","Barangay 4",
    "Barangay 5","Barangay 6","Barangay 7","Barangay 8","Barangay 9",
    "Barangay 10","Barangay 11","Barangay 12","Barangay 13","Barangay 14",
    "Barangay 15","Barangay 16","Barangay 17","Barangay 18","Barangay 19",
    "Barangay 20","Barangay 21","Barangay 22","Barangay 23","Barangay 24",
    "Barangay 25","Barangay 26","Barangay 27","Barangay 28","Barangay 29",
    "Barangay 30","Barangay 31","Barangay 32","Barangay 33","Barangay 34",
    "Barangay 35","Barangay 36","Barangay 37","Barangay 38","Barangay 39",
    "Barangay 40","Barangay 41","Barangay 42","Barangay 43","Barangay 44",
    "Barangay 45","Barangay 46","Barangay 47","Barangay 48","Barangay 49",
    "Barangay 50","Barangay 51","Barangay 52","Barangay 53","Barangay 54",
    "Barangay 55","Barangay 56","Barangay 57","Barangay 58","Barangay 59",
    "Barangay 60","Barangay 61","Barangay 62","Barangay 63","Barangay 64",
    "Barangay 65","Barangay 66","Barangay 67","Barangay 68","Barangay 69",
    "Barangay 70","Barangay 71","Barangay 72","Barangay 73","Barangay 74",
    "Barangay 75","Barangay 76","Barangay 77","Barangay 78","Barangay 79",
    "Barangay 80","Barangay 81","Barangay 82","Barangay 83","Barangay 84",
    "Barangay 85","Barangay 86","Barangay 87","Barangay 88","Barangay 89",
    "Barangay 90","Barangay 91","Barangay 92","Barangay 93","Barangay 94",
    "Barangay 95","Barangay 96","Barangay 97","Barangay 98","Barangay 99",
    "Barangay 100","Barangay 101","Barangay 102","Barangay 103","Barangay 104",
    "Barangay 105","Barangay 106","Barangay 107","Barangay 108","Barangay 109",
    "Barangay 110","Barangay 111","Barangay 112","Barangay 113","Barangay 114",
    "Barangay 115","Barangay 116","Barangay 117","Barangay 118","Barangay 119",
    "Barangay 120","Barangay 121","Barangay 122","Barangay 123","Barangay 124",
    "Barangay 125","Barangay 126","Barangay 127","Barangay 128",
    "Amparo","Bagong Silang","Camarin","Deparo","Kaybiga",
    "Llano","Maybiga","Novaliches","Pag-asa","Pangarap","Sangandaan","Tala",
  ],

  // ── CEBU (REGION VII) ─────────────────────────────────────────────────────
  "Cebu|Cebu City": [
    "Adlaon","Agsungot","Apas","Babag","Basak Pardo","Basak San Nicolas",
    "Binaliw","Bonbon","Buhisan","Bulacao","Buot-Taup Pardo","Calamba",
    "Cambinocot","Capitol Site","Carreta","Central","Cogon Pardo","Cogon Ramos",
    "Day-as","Duljo","Ermita","Guadalupe","Guba","Hippodromo","Inayawan",
    "Kalubihan","Kamagayan","Kamputhaw","Kasambagan","Kinasang-an","Lahug",
    "Lorega San Miguel","Lusaran","Luz","Mabini","Mabolo","Malubog",
    "Mambaling","Nivel Hills","Pardo","Pari-an","Paril","Pasil","Pit-os",
    "Pulangbato","Punta Princesa","Quiot Pardo","Sambag I","Sambag II",
    "San Antonio","San Jose","San Nicolas Central","San Roque","Santa Cruz",
    "Santo Niño","Santo Tomas","Sapangdaku","Sawang Calero","Sinsin","Suba",
    "Sudlon I","Sudlon II","T. Padilla","Talamban","Taptap","Tejero","Tinago",
    "Tipo","Toong","Tulay","Tunghaan","Zapatera",
  ],
  "Cebu|Lapu-Lapu City": [
    "Agus","Babag","Bankal","Baring","Basak","Buaya","Calawisan","Canjulao",
    "Caubian","Caw-oy","Cawhagan","Gun-ob","Ibo","Looc","Mactan","Marigondon",
    "Pajac","Pajo","Punta Engaño","Pusok","Sabang","Santa Rosa","Subabasbas",
    "Talima","Tingo","Tungasan",
  ],
  "Cebu|Mandaue City": [
    "Alang-alang","Bakilid","Banilad","Basak","Cambaro","Canduman","Casili",
    "Casuntingan","Centro","Cubacub","Guizo","Ibabao-Estancia","Jagobiao",
    "Labogon","Looc","Maguikay","Mantuyong","Opao","Pakna-an","Paknaan",
    "Subangdaku","Tabok","Tawason","Tingub","Tipolo","Umapad",
  ],

  // ── DAVAO (REGION XI) ────────────────────────────────────────────────────
  "Davao del Sur|Davao City": [
    "Agdao","Alambre","Alejandra Navarro","Alfonso Angliongto Sr.","Angalan",
    "Atan-awe","Baganihan","Bago Aplaya","Bago Gallera","Bago Oshiro","Bagumbayan",
    "Balengaeng","Baliok","Bangkas Heights","Bantol","Baracatan","Barangay 1-A",
    "Barangay 2-A","Barangay 3-A","Barangay 4-A","Barangay 5-A","Barangay 6-A",
    "Barangay 7-A","Barangay 8-A","Barangay 9-A","Barangay 10-A","Barangay 11-B",
    "Barangay 12-B","Barangay 13-B","Barangay 14-B","Barangay 15-B","Barangay 16-B",
    "Barangay 17-B","Barangay 18-B","Barangay 19-B","Barangay 20-B","Barangay 21-C",
    "Barangay 22-C","Barangay 23-C","Barangay 24-C","Barangay 25-C","Barangay 26-C",
    "Barangay 27-C","Barangay 28-C","Barangay 29-C","Barangay 30-C","Barangay 31-D",
    "Barangay 32-D","Barangay 33-D","Barangay 34-D","Barangay 35-D","Barangay 36-D",
    "Barangay 37-D","Barangay 38-D","Barangay 39-D","Barangay 40-D",
    "Biao Escuela","Biao Guianga","Biao Joaquin","Binugao","Bucana","Buda",
    "Buhangin","Bunawan","Cabantian","Cadalian","Calinan","Callawa","Catalunan Grande",
    "Catalunan Pequeño","Catigan","Cawan","Colosas","Communal","Crossing Bayabas",
    "Dacudao","Dalag","Dalagdag","Daliao","Daliaon Plantation","Datu Salumay",
    "Dominga","Dumoy","Eden","Fatima","Gatungan","Gov. Paciano Bangoy",
    "Gov. Vicente Duterte","Gumalang","Gum-og","Ilang","Inayangan","Indangan",
    "Kap. Tomas Monteverde Sr.","Kilate","Lacson","Lamanan","Lampianao",
    "Langub","Lapu-lapu","Leon Garcia","Lizada","Los Amigos","Losod","Lubogan",
    "Lumiad","Ma-a","Mabuhay","Magsaysay","Magtuod","Mahayag","Malabog",
    "Malagos","Manambulan","Mandug","Manuel Guianga","Mapula","Marapangi",
    "Marilog","Matina Aplaya","Matina Crossing","Matina Pangi","Megkawayan",
    "Mintal","Mudiang","Mulig","New Carmen","New Valencia","Pampanga","Panacan",
    "Panalanoy","Pandaitan","Pangyan","Paquibato","Paradise Embak","Rafael Castillo",
    "Riverside","Romarate","Salapawan","Salaysay","Saloy","San Antonio","San Isidro",
    "Santo Niño","Sasa","Sibulan","Sirawan","Sirib","Suawan","Subasta",
    "Tacunan","Tagakpan","Tagluno","Tagurano","Talomo","Talomo River","Tamayong",
    "Tambobong","Tamugan","Tapak","Tawan-tawan","Tibuloy","Tibungco",
    "Tigatto","Toril","Tugbok","Tuyintungan","Ula","Vicente Hizon Sr.",
    "Waan","Wangan","Wilfredo Aquino","Wines",
  ],

  // ── MISAMIS ORIENTAL (REGION X) ──────────────────────────────────────────
  "Misamis Oriental|Cagayan de Oro City": [
    "Agusan","Balubal","Balulang","Barangay 1","Barangay 2","Barangay 3",
    "Barangay 4","Barangay 5","Barangay 6","Barangay 7","Barangay 8",
    "Barangay 9","Barangay 10","Barangay 11","Barangay 12","Barangay 13",
    "Barangay 14","Barangay 15","Barangay 16","Barangay 17","Barangay 18",
    "Barangay 19","Barangay 20","Barangay 21","Barangay 22","Barangay 23",
    "Barangay 24","Barangay 25","Barangay 26","Barangay 27","Barangay 28",
    "Barangay 29","Barangay 30","Barangay 31","Barangay 32","Barangay 33",
    "Barangay 34","Barangay 35","Barangay 36","Barangay 37","Barangay 38",
    "Barangay 39","Barangay 40","Bayabas","Besigan","Bonbon","Bugo","Bulua",
    "Camaman-an","Cugman","Dansolihon","F.S. Catanico","Gusa","Indahag",
    "Iponan","Kauswagan","Lapasan","Lumbia","Macabalan","Macasandig",
    "Mambuaya","Nazareth","Puntod","San Simon","Tablon","Taglimao",
    "Tignapoloan","Tumpagon","Uplian","Agusan","Carmen","Baikingon",
  ],
  "Misamis Oriental|Iligan City": [
    "Abuno","Acmac","Bagong Silang","Buru-un","Bonbonon","Dalipuga","Del Carmen",
    "Digkilaan","Ditucalan","Dulag","Hinaplanon","Hindang","Kabacsanan","Kalilangan",
    "Kiwalan","Lanipao","Luinab","Mahayahay","Mainit","Mandulog","Maria Cristina",
    "Palao","Panoroganan","Poblacion","Puga-an","Rogongon","San Miguel","San Roque",
    "Santa Elena","Santa Felomina","Santa Filomena","Santiago","Saray","Suarez",
    "Tambacan","Tibanga","Tipanoy","Tominobo Proper","Tominobo Upper",
    "Tubod","Ubaldo Laya","Upper Hinaplanon","Villa Verde",
  ],

  // ── SOUTH COTABATO (REGION XII) ───────────────────────────────────────────
  "South Cotabato|General Santos City": [
    "Apopong","Baluan","Bula","Buayan","Calumpang","City Heights","Conel",
    "Dadiangas East","Dadiangas North","Dadiangas South","Dadiangas West",
    "Fatima","Katangawan","Labangal","Lagao","Ligaya","Mabuhay","Olympog",
    "Pacupe","San Isidro","San Jose","Siguel","Sinawal","Tambler","Tinagacan",
    "Upper Labay",
  ],

  // ── ZAMBOANGA DEL SUR (REGION IX) ────────────────────────────────────────
  "Zamboanga del Sur|Zamboanga City": [
    "Arena Blanco","Ayala","Baliwasan","Baluno","Boalan","Bolong","Buenavista",
    "Bunguiao","Busay","Cabaluay","Cabatangan","Cacao","Calabasa","Calarian",
    "Camino Nuevo","Campo Islam","Canelar","Capisan","Cawit","Culianan",
    "Curuan","Dita","Don Alfaro","Dulian","Dulian Upper","Guiwan",
    "Kasanyangan","La Paz","Labuan","Lamisahan","Landang Gua","Landang Laum",
    "Lapakan","Latuan","Licomo","Limaong","Limpapa","Lubigan","Lumayang",
    "Lumbangan","Lunzuran","Maasin","Malagutay","Mampang","Manalipa",
    "Mangusu","Manicahan","Mariki","Mercedes","Muti","Pamucutan","Pangalcutan",
    "Panubigan","Pasilmanta","Pasonanca","Patalon","Putik","Quiniput",
    "Recodo","Rio Hondo","Salaan","San Jose Cawa-Cawa","San Jose Gusu",
    "San Roque","San Vicente","Sangali","Santa Barbara","Santa Catalina",
    "Santa Maria","Santo Niño","Sibulao","Sinubung","Sinunok","Tagasilay",
    "Tagibilaran","Talabaan","Talon-Talon","Taluksangay","Tetuan","Tictapul",
    "Tigbalabag","Tigtabon","Tolosa","Tugbungan","Tulungatung","Tumaga",
    "Tumalutab","Tumitus","Victoria","Vitali","Wakaf","Zambowood",
  ],

  // ── LANAO DEL NORTE (REGION X) ────────────────────────────────────────────
  "Lanao del Norte|Iligan City": [],  // handled above under Misamis Oriental

  // ── LEYTE (REGION VIII) ───────────────────────────────────────────────────
  "Leyte|Tacloban City": [
    "Anibong","Bagacay","Barangay 1","Barangay 2","Barangay 3","Barangay 4",
    "Barangay 5","Barangay 6","Barangay 7","Barangay 8","Barangay 9",
    "Barangay 10","Barangay 11","Barangay 12","Barangay 13","Barangay 14",
    "Barangay 15","Barangay 16","Barangay 17","Barangay 18","Barangay 19",
    "Barangay 20","Barangay 21","Barangay 22","Barangay 23","Barangay 24",
    "Barangay 25","Barangay 26","Barangay 27","Barangay 28","Barangay 29",
    "Barangay 30","Barangay 31","Barangay 32","Barangay 33","Barangay 34",
    "Barangay 35","Barangay 36","Barangay 37","Barangay 38","Barangay 39",
    "Barangay 40","Barangay 41","Barangay 42","Barangay 43","Barangay 44",
    "Barangay 45","Barangay 46","Barangay 47","Barangay 48","Barangay 49",
    "Barangay 50","Barangay 51","Barangay 52","Barangay 53","Barangay 54",
    "Barangay 55","Barangay 56","Barangay 57","Barangay 58","Barangay 59",
    "Barangay 60","Barangay 61","Barangay 62","Barangay 63","Barangay 64",
    "Barangay 65","Barangay 66","Barangay 67","Barangay 68","Barangay 69",
    "Barangay 70","Barangay 71","Barangay 72","Barangay 73","Barangay 74",
    "Barangay 75","Barangay 76","Barangay 77","Barangay 78","Barangay 79",
    "Barangay 80","Barangay 81","Barangay 82","Barangay 83","Barangay 84",
    "Barangay 85","Barangay 86","Barangay 87","Barangay 88","Barangay 89",
    "Barangay 90","Barangay 91","Barangay 92","Barangay 93","Barangay 94",
    "Barangay 95","Barangay 96","Barangay 97","Barangay 98","Barangay 99",
    "Barangay 100","Barangay 101","Barangay 102","Barangay 103","Barangay 104",
    "Barangay 105","Barangay 106","Barangay 107","Barangay 108","Barangay 109",
    "Barangay 110","Barangay 111","Barangay 112","Barangay 113","Barangay 114",
    "Barangay 115","Barangay 116","Barangay 117","Barangay 118","Barangay 119",
    "Barangay 120","Barangay 121","Barangay 122","Barangay 123","Barangay 124",
    "Barangay 125","Barangay 126","Barangay 127","Barangay 128",
    "Caibaan","Calanipawan","Campetic","Carayman","diit","Fatima",
    "Marasbaras","New Kawayan","Nula-tula","Old Kawayan","Palanog",
    "Salvacion","San Jose","Santa Elena","Santo Niño","Suhi","Surigao",
    "Tagapuro","V&G Better Homes Subdivision","Valeria",
  ],

  // ── ILOILO (REGION VI) ────────────────────────────────────────────────────
  "Iloilo|Iloilo City": [
    "Baldoza","Bantud","Bito-on","Bo. Obrero","Bolilao","Bonifacio",
    "Boulevard","Calaparan","City Proper","Compania","Cor-Jesus","Delgado",
    "Di-an","Dungon","Dungon A","Dungon B","East Timawa","Fajardo",
    "Flores","Gustilo","Hinactaogan","Hipodromo","Indag-an","Jalandoni",
    "Jaro","Jereos","Kahirup","La Paz","Lanit","Lapaz","Lapuz Norte",
    "Lapuz Sur","Libertad","Loboc","Lopez Jaena","Luna","Maasin","Macabahay",
    "Mactan","Mansaya-Lapuz","Marti","Montinola","Muelle Loney","Nabitasan",
    "Navais","Nonoy","North Avanceña","North Fundidor","North San Jose",
    "Oñate de Leon","Osmena","Pale Benedicto","Quintin Salas","Rizal",
    "San Isidro","San Jose","San Nicolas","Santa Cruz","Santiago",
    "Santo Niño Norte","Santo Niño Sur","Santo Rosario","Seminario","Simon Ledesma",
    "South Fundidor","South San Jose","Taal","Tabuc Suba","Talon","Tan-awan",
    "Tapuac","Ticud",
  ],

  // ── NEGROS OCCIDENTAL (REGION VI) ────────────────────────────────────────
  "Negros Occidental|Bacolod City": [
    "Alangilan","Alijis","Banago","Barangay 1","Barangay 2","Barangay 3",
    "Barangay 4","Barangay 5","Barangay 6","Barangay 7","Barangay 8",
    "Barangay 9","Barangay 10","Barangay 11","Barangay 12","Barangay 13",
    "Barangay 14","Barangay 15","Barangay 16","Barangay 17","Barangay 18",
    "Barangay 19","Barangay 20","Barangay 21","Barangay 22","Barangay 23",
    "Barangay 24","Barangay 25","Barangay 26","Barangay 27","Barangay 28",
    "Barangay 29","Barangay 30","Barangay 31","Barangay 32","Barangay 33",
    "Barangay 34","Barangay 35","Barangay 36","Barangay 37","Barangay 38",
    "Barangay 39","Barangay 40","Bata","Cabug","Estefania","Felisa",
    "Granada","Handumanan","Lag-asan","Mabini","Mandalagan","Mansilingan",
    "Montevista","Pahanocoy","Punta Taytay","Singcang-Airport","Sum-ag","Taculing",
    "Tangub","Taslon","Vista Alegre",
  ],

  // ── BENGUET / BAGUIO CITY ────────────────────────────────────────────────
  "Benguet|Baguio City": [
    "Abanao-Zandueta-Kayong-Chugum-Otek","Alfonso Tabora","Ambiong",
    "Andres Bonifacio","Apugan-Loakan","Asin Road","Aurora Hill Proper",
    "Bagong Lipunan ng Crame","Bakakeng Central","Bakakeng Norte",
    "Balsigan","Bayan Park East","Bayan Park Village","Bayan Park West",
    "Brookside","Brookspoint","Cabinet Hill-Teacher's Camp","Camp 7",
    "Camp 8","Camp Allen","Campo Filipino","City Camp Central",
    "City Camp Proper","Country Club Village","Dagsian Lower","Dagsian Upper",
    "Dizon Subdivision","Dominican Hill-Mirador","Dontogan",
    "DPS Area","Engineers Hill","Fairview Village","Ferdinand",
    "Fort del Pilar","Gabriela Silang","General Luna","Gibraltar",
    "Greenwater Village","Guisad Central","Guisad Sorong","Happy Hollow",
    "Happy Homes","Harrison-Claudio Carantes","Hillside","Holy Ghost Extension",
    "Holy Ghost Proper","Honeymoon (Honeymoon Road)","Imelda R. Marcos (La Trinidad Road)",
    "Irisan","Kabayanihan","Kayang-Hilltop","Kayang-Kayang","Kias","Legarda-Burnham-Kisad",
    "Loakan Apugan","Loakan Proper","Lopez Jaena","Lourdes Subdivision Extension",
    "Lourdes Subdivision Proper","Lower Campo Filipino","Lower Dagsian","Lower Magsaysay",
    "Lower Quezon Hill","Lower Rock Quarry","Lualhati","Lucnab",
    "Magsaysay Private Road","Magsaysay Lower","Magsaysay Upper","Manuel A. Roxas",
    "Market Subdivision Upper","Middle Quezon Hill","Military Cut-off",
    "Mines View Park","Modern Site East","Modern Site West","MRR-Queen of Peace",
    "New Lucban","Pacdal","Padre Burgos","Padre Zamora",
    "Palma-Urbano","Phil-Am","Pinget","Pinsao Pilot Project","Pinsao Proper",
    "Poliwes","Pucay","Puguis","Quirino Hill East","Quirino Hill Lower",
    "Quirino Hill Middle","Quirino Hill West","Quirino-Magsaysay-Milflores",
    "Rock Quarry Lower","Rock Quarry Middle","Rock Quarry Upper",
    "Saint Joseph Village","Salud Mitra","San Antonio Village",
    "San Luis Village","San Roque Village","San Vicente",
    "Santo Rosario-Lakan Quezon-Idaban","Sanitary Camp Lower","Sanitary Camp Upper",
    "Santo Tomas Proper","Scout Barrio","Session Road Area","Slaughter House Area",
    "SLU-SVP Housing Village","South Drive","Teodora Alonzo","Trancoville",
    "Upper Dagsian","Upper Magsaysay","Upper Quezon Hill","Upper Rock Quarry",
  ],
};

export function getBarangays(province: string, city: string): string[] {
  return PH_BARANGAYS[`${province}|${city}`] ?? [];
}
